// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
)

type McpHubServer struct {
	ID           string
	UserID       string
	McpServerID  string
	Status       string
	Transport    string
	Capabilities json.RawMessage
	AuthType     string
	AuthValue    json.RawMessage
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type McpServer struct {
	ID          string
	Name        string
	Url         string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type McpTool struct {
	ID             string
	UserID         string
	OriginalName   string
	ModifiedName   string
	McpHubServerID string
	InputSchema    json.RawMessage
	Annotations    json.RawMessage
	Status         string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type McpVirtualServer struct {
	ID        string
	UserID    string
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ToolsVirtualServer struct {
	McpVirtualServerID string
	ToolID             string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type User struct {
	ID        string
	Username  string
	Role      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
