-- +goose Up
-- Schema for Global MCP Server (MySQL)
CREATE TABLE IF NOT EXISTS users (
  id CHAR(22) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mcp_servers (
  id CHAR(22) PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  url VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mcp_hub_servers (
  id CHAR(22) PRIMARY KEY,
  user_id CHAR(22) NOT NULL,
  mcp_server_id CHAR(22) NOT NULL,
  status VARCHAR(30) NOT NULL,
  transport VARCHAR(30) NOT NULL,
  capabilities JSON,
  auth_type VARCHAR(30) NOT NULL,
  auth_value JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_hub_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_hub_mcp_srv FOREIGN KEY (mcp_server_id) REFERENCES mcp_servers(id) ON DELETE CASCADE,
  UNIQUE KEY uq_user_server (user_id, mcp_server_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mcp_tools (
  id CHAR(22) PRIMARY KEY,
  user_id CHAR(22) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  modified_name VARCHAR(255) NOT NULL,
  mcp_hub_server_id CHAR(22) NOT NULL,
  input_schema JSON,
  annotations JSON,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tools_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_tools_hub FOREIGN KEY (mcp_hub_server_id) REFERENCES mcp_hub_servers(id) ON DELETE CASCADE,
  UNIQUE KEY uq_user_modified (user_id, modified_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mcp_virtual_servers (
  id CHAR(22) PRIMARY KEY,
  user_id CHAR(22) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tools_virtual_servers (
  mcp_virtual_server_id CHAR(22) NOT NULL,
  tool_id CHAR(22) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (mcp_virtual_server_id, tool_id),
  CONSTRAINT fk_vs_tool_vs FOREIGN KEY (mcp_virtual_server_id) REFERENCES mcp_virtual_servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_vs_tool_tool FOREIGN KEY (tool_id) REFERENCES mcp_tools(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
DROP TABLE IF EXISTS tools_virtual_servers;
DROP TABLE IF EXISTS mcp_virtual_servers;
DROP TABLE IF EXISTS mcp_tools;
DROP TABLE IF EXISTS mcp_hub_servers;
DROP TABLE IF EXISTS mcp_servers;
DROP TABLE IF EXISTS users;
